### ISSUE TITLE
Voting for update the ECNS registrar. Allow to extract funds from the stale Deeds.

### ISSUE THREAD

**Issue by sgitt-vassky** [EthereumCommonwealth/Roadmap#32]
### Yes, let's update it.

To vote for this item, send DEX tokens to this contract: 0x56696968c23cce54dfea7349c7d5c96e41f38e77

### No, leave it as is.

To vote for this item, send DEX tokens to this contract: 0xe2ddee6187d6e231ae540bd7eac2dbd83a7448d9

p.s. compiled with solc 0.4.17 + optimization.
bytecode keccak-256 hash `0x83a3636f93df74b400cf70ffe4f01835189b8c42df729068fe8695aab044eca9`

**Comment by Dexaran** [comment]
Confirmed.

Voting results would be calculated at 10/15/2017

**Comment by Dexaran** [comment]
Original proposal: https://github.com/EthereumCommonwealth/Roadmap/issues/30#issue-256462604

### Proposal implementation summary

1. Apply changes to `Deed` contract of the ECNS.

2. Apply changes to `HashRegistrar` contract of the ECNS to allow it to deploy new Deeds.

3. Re-deploy ECNS HashRegistrar.

These changes will allow Deeds to "expire". The validity of each Deed expires 7 days after the moment of its deployment.
Everyone will be allowed to call a special function at the Deed contract to destroy the expired Deed. The address of the caller will receive 5% of the Deed's funds to incentivise users to clear expired Deeds. 95% of Deed's funds would go to the Ethereum Commonwealth revenue destribution address.

**Comment by hanzi13** [comment]
As I see there were not too many voting attempts.

Previously there was talking about cold staking of DEX tokens.
How about somehow merging these two functions, that only the tokens that have been used for voting would receive staking rewards. This could incentivize voting.
I don't know whether it's even possible to do or not, it's just a vague idea.

**Comment by Dexaran** [comment]
@hanzi13 

Staking model for DEX token is an interesting idea. At the other hand, it doesn't introduce any really valuable updates because it will not affect the proportion of tokens distribution.

As for your proposal, this will incentivise token holders to vote. Active voters will be allowed to stake and increase their share of token supply. Passive token holders will not stake and their share of tokens will decrease with time. Their voices weight will decrease as well.

I think that it is technically possible. I'm not against it but it doesn't seem a main goal for me right now.

**Comment by Dexaran** [comment]
Voting results computed at block 4660000.

## YES ( 100% )

848 DEX

## NO ( 0% )

0 DEX

The proposal considered accepted. The Hash Registrar will be updated and re-deployed as soon as the new version will be developed and tested.
